### ISSUE TITLE
Nested sampling retrieval crashes when wavelength bins for multiple instruments are passed

### ISSUE THREAD

**Issue by joshjchayes** [ideasrule/platon#43]
Hi, 

I am trying to run retrieval on some simulated composite spectra for 3 different instruments. When I run retrieval using just one of each of the instruments, there is no problem, but when I combine them in any way, I get the following error message. I assume that this issue is due to the wavelength bins being passed to the retriever. 

```
/data/jhayes/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/data/jhayes/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Exception while calling loglikelihood function:
  params: [ 2.85511517e+27  2.39638339e+03 -7.60211364e-01  1.72730302e+00
 -1.43587464e+00]
  args: []
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/dynesty-1.0.0-py3.7.egg/dynesty/dynesty.py", line 860, in __call__
    return self.func(x, *self.args, **self.kwargs)
  File "/data/jhayes/EGP_classes/scripts/ML/platon-4.0-py3.7.egg/platon/combined_retriever.py", line 356, in multinest_ln_like
    eclipse_depths, eclipse_errors)
  File "/data/jhayes/EGP_classes/scripts/ML/platon-4.0-py3.7.egg/platon/combined_retriever.py", line 132, in _ln_like
    part_size=part_size, ri=ri, full_output=True)
  File "/data/jhayes/EGP_classes/scripts/ML/platon-4.0-py3.7.egg/platon/transit_depth_calculator.py", line 531, in compute_depths
    binned_wavelengths, binned_depths, stellar_spectrum = self._get_binned_corrected_depths(transit_depths, T_star, T_spot, spot_cov_frac)
  File "/data/jhayes/EGP_classes/scripts/ML/platon-4.0-py3.7.egg/platon/transit_depth_calculator.py", line 302, in _get_binned_corrected_depths
    binned_depth = np.average(depths[cond] * correction_factors[cond], weights=stellar_spectrum[cond])
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 422, in average
    "Weights sum to zero, can't be normalized")
ZeroDivisionError: Weights sum to zero, can't be normalized
```

The instruments I am using have overlapping wavelength ranges and consequently some of the bins overlap. Is this a known issue where wavelength bins can't overlap? Alternatively, I have supplied the bins grouped by instrument - should they be arranged in ascending wavelength order? 

Thanks in advance

**Comment by ideasrule** [comment]
Hi Josh,

Overlapping wavelength bins shouldn't be an issue, and neither should out-of-order wavelength bins.  I think the issue is that one of your wavelength bins is smaller than the spacing in the wavelength grid (which is R=1000).  Can you check if this the case?  In general, for any bin, lambda/(lambda_max - lambda_min) should be less than 100 (and ideally less than 50).  If this isn't possible with the R=1000 opacities, consider using the R=10,000 data files: http://www.astro.caltech.edu/~mz/absorption.html

Thanks for using PLATON!

**Comment by joshjchayes** [comment]
Hi there, 

It turned out I had a bug which was giving me negative resolutions (don't ask...). Thanks for your help!
